function [XOdo] = simulateRobot_omni4(X0,Odo,TOdo,RobotParam)

  % Initialization: Data
  [itf,numWh] = size(Odo);
  XOdo = zeros(itf,3);
  
  % Initialization: Robot parameters
  ngear  = RobotParam.ngear;
  encRes = RobotParam.encRes;
  L      = RobotParam.L;
  D      = RobotParam.D;
  J = [
                   1/4 ,               -1/4 ,                1/4 ,               -1/4 ; ...
                  -1/4 ,               -1/4 ,                1/4 ,                1/4 ; ...
    -1/(2*(L(1)+L(2))) , -1/(2*(L(1)+L(2))) , -1/(2*(L(1)+L(2))) , -1/(2*(L(1)+L(2)))   ...
  ];
  Jinv = J'/(J*J');

  % Simulate robot
  XOdo(1,:) = X0(1,:);
  for i=2:itf
    % Linear and angular displacements
    deltaWh  = pi.*D.*Odo(i,:)./(ngear*encRes);
    deltaRob = (J * deltaWh')';

    % Odometry pose
    if ( abs(deltaRob(3))/TOdo < 1e-5 )
      XOdo(i,1) =                      ...
        XOdo(i-1,1)                  + ...
        deltaRob(1)*cos(XOdo(i-1,3)) - ...
        deltaRob(2)*sin(XOdo(i-1,3));
      XOdo(i,2) =                      ...
        XOdo(i-1,2)                  + ...
        deltaRob(1)*sin(XOdo(i-1,3)) + ...
        deltaRob(2)*cos(XOdo(i-1,3));
    else
      XOdo(i,1) =                                                                                                    ...
        XOdo(i-1,1)                                                                                                + ...
        (deltaRob(1)*sin(deltaRob(3))+deltaRob(2)*(cos(deltaRob(3))-1))*cos(XOdo(i-1,3)+deltaRob(3)/2)/deltaRob(3) - ...
        (deltaRob(1)*(1-cos(deltaRob(3)))+deltaRob(2)*sin(deltaRob(3)))*sin(XOdo(i-1,3)+deltaRob(3)/2)/deltaRob(3);
      XOdo(i,2) =                                                                                                    ...
        XOdo(i-1,2)                                                                                                + ...
        (deltaRob(1)*sin(deltaRob(3))+deltaRob(2)*(cos(deltaRob(3))-1))*sin(XOdo(i-1,3)+deltaRob(3)/2)/deltaRob(3) + ...
        (deltaRob(1)*(1-cos(deltaRob(3)))+deltaRob(2)*sin(deltaRob(3)))*cos(XOdo(i-1,3)+deltaRob(3)/2)/deltaRob(3);
    end
    XOdo(i,3) = XOdo(i-1,3) + deltaRob(3);
  end
end